---
- name: Nginx Deployment
  hosts: all
  become: yes
  tasks:
  - name: Install python3-apt
    package:
      name: python3-apt
      state: present

  - name: Install Nginx
    package:
      name: nginx
      state: present

  - name: Start and enable Nginx service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Deploy custom index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
    notify: restart nginx

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
