---
- name: Nginx Deployment
  hosts: all
  become: yes

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
      executable: /usr/bin/apt-get
    
  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Start and enable Nginx service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Deploy custom index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
    notify: restart nginx

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
